server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://provider-studio:5700;
        proxy_set_header Host $host;
    }
    location /health {
        proxy_pass http://provider-studio:5700;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
