// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProviderStudio.Data;

#nullable disable

namespace ProviderStudio.Migrations
{
    [DbContext(typeof(StudioDbContext))]
    [Migration("20260525083306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ProviderStudio.Data.Entities.DbConnectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiAuthHeaderEnc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiAuthType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiDefaultHeaders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraOptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordEnc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("DbConnections");
                });

            modelBuilder.Entity("ProviderStudio.Data.Entities.OperationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DbConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PushChangeQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PushPollIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryTarget")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DbConnectionId");

                    b.HasIndex("ProviderId", "Pattern")
                        .IsUnique();

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("ProviderStudio.Data.Entities.ParamMappingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiTarget")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "JsonPath");

                    b.ToTable("ParamMappings");
                });

            modelBuilder.Entity("ProviderStudio.Data.Entities.ProviderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BridgeGrpcUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecretEnc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngestionBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngestionTokenEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("ProviderStudio.Data.Entities.DbConnectionEntity", b =>
                {
                    b.HasOne("ProviderStudio.Data.Entities.ProviderEntity", "Provider")
                        .WithMany("DbConnections")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ProviderStudio.Data.Entities.OperationEntity", b =>
                {
                    b.HasOne("ProviderStudio.Data.Entities.DbConnectionEntity", "DbConnection")
                        .WithMany("Operations")
                        .HasForeignKey("DbConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProviderStudio.Data.Entities.ProviderEntity", "Provider")
                        .WithMany("Operations")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbConnection");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ProviderStudio.Data.Entities.ParamMappingEntity", b =>
                {
                    b.HasOne("ProviderStudio.Data.Entities.OperationEntity", "Operation")
                        .WithMany("ParamMappings")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("ProviderStudio.Data.Entities.DbConnectionEntity", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("ProviderStudio.Data.Entities.OperationEntity", b =>
                {
                    b.Navigation("ParamMappings");
                });

            modelBuilder.Entity("ProviderStudio.Data.Entities.ProviderEntity", b =>
                {
                    b.Navigation("DbConnections");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
